/* export const CHANGE_USER_INFO_NAME = 'CHANGE_USER_INFO_NAME';
export const CHANGE_USER_INFO_EMAIL = 'CHANGE_USER_INFO_EMAIL';
export const CHANGE_USER_INFO_PASSWORD = 'CHANGE_USER_INFO_PASSWORD';
 */
