export const ADD_BUN_TO_CONSTRUCTOR = 'ADD_BUN_TO_CONSTRUCTOR';
export const ADD_STUFFING_ELEMENT_TO_CONSTRUCTOR = 'ADD_STUFFING_ELEMENT_TO_CONSTRUCTOR';
export const DELETE_STUFFING_ELEMENT_FROM_CONSTRUCTOR = 'DELETE_STUFFING_ELEMENT_FROM_CONSTRUCTOR';
export const REORDER_STUFFING_ELEMENTS = 'REORDER_STUFFING_ELEMENTS';
export const CONSTRUCTOR_CLEANUP = 'CONSTRUCTOR_CLEANUP';
