export const REGISTRATION_USER_REQUEST: 'REGISTRATION_USER_REQUEST' = 'REGISTRATION_USER_REQUEST';
export const REGISTRATION_USER_SUCCESS: 'REGISTRATION_USER_SUCCESS' = 'REGISTRATION_USER_SUCCESS';
export const REGISTRATION_USER_FAILED: 'REGISTRATION_USER_FAILED' = 'REGISTRATION_USER_FAILED';

export const LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST' = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS' = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED: 'LOGIN_USER_FAILED' = 'LOGIN_USER_FAILED';

export const LOGOUT_USER_REQUEST: 'LOGOUT_USER_REQUEST' = 'LOGOUT_USER_REQUEST';
export const LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS' = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILED: 'LOGOUT_USER_FAILED' = 'LOGOUT_USER_FAILED';

export const FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST' = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS' = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED: 'FORGOT_PASSWORD_FAILED' = 'FORGOT_PASSWORD_FAILED';

export const RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST' = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS' = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED: 'RESET_PASSWORD_FAILED' = 'RESET_PASSWORD_FAILED';

export const GET_USERDATA_REQUEST: 'GET_USERDATA_REQUEST' = 'GET_USERDATA_REQUEST';
export const GET_USERDATA_SUCCESS: 'GET_USERDATA_SUCCESS' = 'GET_USERDATA_SUCCESS';
export const GET_USERDATA_FAILED: 'GET_USERDATA_FAILED' = 'GET_USERDATA_FAILED';

export const REFRESH_USERDATA_REQUEST: 'REFRESH_USERDATA_REQUEST' = 'REFRESH_USERDATA_REQUEST';
export const REFRESH_USERDATA_SUCCESS: 'REFRESH_USERDATA_SUCCESS' = 'REFRESH_USERDATA_SUCCESS';
export const REFRESH_USERDATA_FAILED: 'REFRESH_USERDATA_FAILED' = 'REFRESH_USERDATA_FAILED';

export const UPDATE_TOKEN_REQUEST: 'UPDATE_TOKEN_REQUEST' = 'UPDATE_TOKEN_REQUEST';
export const UPDATE_TOKEN_SUCCESS: 'UPDATE_TOKEN_SUCCESS' = 'UPDATE_TOKEN_SUCCESS';
export const UPDATE_TOKEN_FAILED: 'UPDATE_TOKEN_FAILED' = 'UPDATE_TOKEN_FAILED';
